version: '3'
services:
  web:
    build: .
    command: >
      sh  -c  "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
    - "8000:8000"
    volumes:
      - ./KryptoAPI/:/code
    env_file:
      - ./KryptoAPI/.docker.env
    depends_on:
      - db
  
  db:
    image: postgres:14rc1-alpine3.14
    env_file:
      - ./KryptoAPI/.docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    env_file:
      - ./KryptoAPI/.docker.env
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
  
  celery-worker:
    build: .
    command: sh -c 'sleep 8; celery -A KryptoAPI worker -l INFO'
    env_file:
      - ./KryptoAPI/.docker.env
    volumes:
      - ./KryptoAPI/:/code
    depends_on:
      - db
      - rabbitmq
  
  celery-beat:
    build: .
    command: sh -c 'sleep 10; celery -A KryptoAPI beat -l debug'
    env_file:
      - ./KryptoAPI/.docker.env
    volumes:
      - ./KryptoAPI/:/code
    depends_on:
      - db
      - rabbitmq
      - celery-worker
volumes:
  pgdata: {}
